[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
btclib = { path = "../lib" }
tokio = { version = "1.43.0", features = ["full"] }
clap = { version = "4.5.27", features = ["derive"] }
anyhow = { version = "1.0.95" }
flume = "0.11.1"
tokio-util = { version ="0.7.13" }
